### ISSUE TITLE
mdpopups has no attrubtes

### ISSUE THREAD

**Issue by TwoClocks** [facelessuser/sublime-markdown-popups#137]
`mdpopup_test` works fine. But I can't use it in my own code. Or even the python repl:

```
>>> import mdpopups
>>> mdpopups.version()
Traceback (most recent call last):
  File "__main__", line 1, in <module>
AttributeError: module 'mdpopups' has no attribute 'version'
>>> print(mdpopups.__dir__())
['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__file__', '__path__']
```

Is there some magic that I'm missing?

**Comment by facelessuser** [comment]
Can you give me more information? Is this in the Sublime console? If so, are you using the console in Python 3.8 mode or 3.3 mode. Mdpopus only works in Python 3.3 because Package Control has still yet to provide Python 3.8 dependency support.

**Comment by TwoClocks** [comment]
Yes, I'm using the sublime console. Yep, it's 3.8. So is the `User` package my code is in.

I moved my code to it's own directory, and set the python version. Works fine now.

Thanks!
